# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # -- Main Window --
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 822)
        MainWindow.setAutoFillBackground(True)

        # -- central widget --
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # -- horizontalLayout --
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.setupLabelImageUi(MainWindow)
        
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(-1, 569, 1001, 201))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.setupButtonUi(MainWindow)
        
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(810, 20, 191, 531))
        self.toolBox.setObjectName("toolBox")
        self.Parametres_Page = QtWidgets.QWidget()
        self.Parametres_Page.setGeometry(QtCore.QRect(0, 0, 191, 479))
        self.Parametres_Page.setObjectName("Parametres_Page")
        self.toolBox.addItem(self.Parametres_Page, "")
        self.Textures_Page = QtWidgets.QWidget()
        self.Textures_Page.setGeometry(QtCore.QRect(0, 0, 191, 479))
        self.Textures_Page.setObjectName("Textures_Page")
        self.toolBox.addItem(self.Textures_Page, "")

        MainWindow.setCentralWidget(self.centralwidget)

        self.setupMenuBar(MainWindow)

        self.retranslateUi(MainWindow)

        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    # ---- Setup Ui Fonction ----
    def setupLabelImageUi(self, MainWindow):
        # --  --
        self.label_image_original = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_image_original.setFont(font)
        self.label_image_original.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_original.setObjectName("label_image_original")
        self.horizontalLayout.addWidget(self.label_image_original)


        self.label_image_pixel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_image_pixel.setFont(font)
        self.label_image_pixel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_pixel.setObjectName("label_image_pixel")
        self.horizontalLayout.addWidget(self.label_image_pixel)


    def setupButtonUi(self, MainWindow):
        # --  --
        self.pushButton_ouvrir = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_ouvrir.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_ouvrir.setObjectName("pushButton_ouvrir")
        self.pushButton_ouvrir.clicked.connect(self.openImage)
        self.horizontalLayout_4.addWidget(self.pushButton_ouvrir)

        # --  --
        self.pushButton_generer = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_generer.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_generer.setObjectName("pushButton_generer")
        self.horizontalLayout_4.addWidget(self.pushButton_generer)

        # --  --
        self.pushButton_exporter = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_exporter.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_exporter.setObjectName("pushButton_exporter")
        self.horizontalLayout_4.addWidget(self.pushButton_exporter)


    def setupMenuBar(self, MainWindow):
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNouveau = QtWidgets.QAction(MainWindow)
        self.actionNouveau.setObjectName("actionNouveau")
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionOuvrir_une_image = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_une_image.setObjectName("actionOuvrir_une_image")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_une_copie = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_une_copie.setObjectName("actionEnregistrer_une_copie")
        self.actionImporter_une_Palette = QtWidgets.QAction(MainWindow)
        self.actionImporter_une_Palette.setObjectName("actionImporter_une_Palette")
        self.actionExporter_une_Palette = QtWidgets.QAction(MainWindow)
        self.actionExporter_une_Palette.setObjectName("actionExporter_une_Palette")
        self.actionExporter_Pixel_Art = QtWidgets.QAction(MainWindow)
        self.actionExporter_Pixel_Art.setObjectName("actionExporter_Pixel_Art")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionNouveau)
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionOuvrir_une_image)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_une_copie)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionImporter_une_Palette)
        self.menuFichier.addAction(self.actionExporter_une_Palette)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionExporter_Pixel_Art)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_image_original.setText(_translate("MainWindow", "ImageOriginals"))
        self.label_image_pixel.setText(_translate("MainWindow", "ImagePixelise"))

        self.pushButton_ouvrir.setText(_translate("MainWindow", "Ouvir"))
        self.pushButton_generer.setText(_translate("MainWindow", "Générer"))
        self.pushButton_exporter.setText(_translate("MainWindow", "Exporter"))

        self.toolBox.setItemText(self.toolBox.indexOf(self.Parametres_Page), _translate("MainWindow", "Parametres"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Textures_Page), _translate("MainWindow", "Textures"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.actionNouveau.setText(_translate("MainWindow", "Nouveau"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionOuvrir_une_image.setText(_translate("MainWindow", "Ouvrir une image"))
        self.actionEnregistrer.setText(_translate("MainWindow", "Enregistrer "))
        self.actionEnregistrer_une_copie.setText(_translate("MainWindow", "Enregistrer une copie"))
        self.actionImporter_une_Palette.setText(_translate("MainWindow", "Importer une Palette"))
        self.actionExporter_une_Palette.setText(_translate("MainWindow", "Exporter une Palette"))
        self.actionExporter_Pixel_Art.setText(_translate("MainWindow", "Exporter Pixel Art"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))


    # ---- Action Fonction ----

    def openImage(self):
        fname = QFileDialog.getOpenFileName()
        print(fname)
        self.label_image_original.setPixmap(QtGui.QPixmap(fname[0]))
        self.label_image_original.setScaledContents(True)





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


